"""Step 28: export deployment artifacts (no patient data) to deploy/: the validated contact-history model (M2) as trained on the training set,
an M2 refit on all eligible decision points through 2026-06-07 for deployment, the exact feature column list and definitions, the 20% flagging
threshold and decile cutpoints, the hand-scorable points score, the day-7 rule, and the uplift (return-if-attempted) T-learner used to order the list."""
import json, pathlib, numpy as np, pandas as pd, joblib
from sklearn.ensemble import HistGradientBoostingClassifier, GradientBoostingRegressor
D = pathlib.Path("data_cache"); R = pathlib.Path("results"); OUT = pathlib.Path("deploy"); OUT.mkdir(exist_ok=True); HP = json.load(open(R/"hyperparameters.json"))["gbm"]
F = pd.read_parquet(D/"dp_features.parquet"); O = pd.read_parquet(D/"dp_outcomes.parquet"); df = F.merge(O[["decision_id","eligible","y_primary"]], on="decision_id"); df = df[df.eligible == 1].reset_index(drop=True)
STRUCT = ["age","risk_percentile","tier1_flg","days_from_zd","days_since_last_adt"] + [f"adt_all_prior_{w}d" for w in [30,90,180,365]] + [c for c in ["diabetes","htn","chf","copd","sud","any_bh","mdd","asthma","polypharmacy","high_ed_ip","no_pcp_last_10mo"] if c in df.columns]
HIST = ["n_prior","n_prior_90","n_prior_30","days_since_last_contact","chw90","pharm90","cpht90","ther90","cc90","inp90","textmod90","n_disc90","gap_mean","gap_max","cur_inp","cur_textmod","note_len","goals_open","goals_completed_before","goals_social","goals_clinical","goals_bh"]
cat_struct = pd.get_dummies(df[["gender","race","state"]].fillna("u"), drop_first=True, dtype=float); cat_hist = pd.get_dummies(df[["cur_rg","prev_rg","contact_type","encounter_type"]].fillna("u"), drop_first=True, dtype=float)
X = pd.concat([df[STRUCT].astype(float), cat_struct, df[HIST].astype(float), cat_hist], axis=1).fillna(0); y = df.y_primary.values; tr = (df.training_era == 1).values
m_val = HistGradientBoostingClassifier(**HP).fit(X.values[tr], y[tr]); m_all = HistGradientBoostingClassifier(**HP).fit(X.values, y)
joblib.dump(m_val, OUT/"m2_validated_trained_before_2025-07-01.joblib"); joblib.dump(m_all, OUT/"m2_deploy_refit_all_data_through_2026-06-07.joblib")
p_tr = m_val.predict_proba(X.values[tr])[:,1]; p_all = m_all.predict_proba(X.values)[:,1]
DEF = {"age": "age in years at activation", "risk_percentile": "acute-care risk percentile at activation (Signal)", "tier1_flg": "tier 1 flag at activation", "days_from_zd": "days from activation to this contact", "days_since_last_adt": "days since last ADT event before this contact (999 if none)",
       "adt_all_prior_30d": "ADT events in the 30 days before the contact", "adt_all_prior_90d": "ADT events in the prior 90 days", "adt_all_prior_180d": "ADT events in the prior 180 days", "adt_all_prior_365d": "ADT events in the prior 365 days",
       "diabetes": "condition flag", "htn": "condition flag", "chf": "condition flag", "copd": "condition flag", "sud": "condition flag", "any_bh": "any behavioral health condition flag", "mdd": "condition flag", "asthma": "condition flag", "polypharmacy": "flag", "high_ed_ip": "high prior ED or inpatient use flag", "no_pcp_last_10mo": "no primary care visit in prior 10 months flag",
       "n_prior": "completed contacts before this one", "n_prior_90": "completed contacts in the prior 90 days", "n_prior_30": "completed contacts in the prior 30 days", "days_since_last_contact": "days since previous completed contact (999 if none)",
       "chw90": "CHW contacts in prior 90 days", "pharm90": "clinical pharmacist contacts in prior 90 days", "cpht90": "pharmacy technician contacts in prior 90 days", "ther90": "therapist contacts in prior 90 days", "cc90": "care coordinator contacts in prior 90 days", "inp90": "in-person contacts in prior 90 days", "textmod90": "text or email contacts in prior 90 days", "n_disc90": "distinct disciplines in prior 90 days",
       "gap_mean": "mean days between the last six contacts (999 if fewer than two)", "gap_max": "maximum gap in days between prior contacts (999 if fewer than two)", "cur_inp": "this contact was in person", "cur_textmod": "this contact was text or email", "note_len": "characters in this contact's note", "goals_open": "open goals at the contact", "goals_completed_before": "goals completed before the contact", "goals_social": "goals in the social category", "goals_clinical": "goals in the clinical category", "goals_bh": "goals in the behavioral health category"}
spec = {"model": "sklearn HistGradientBoostingClassifier", "hyperparameters": HP, "columns_in_order": list(X.columns), "definitions": DEF, "one_hot": {"prefix": "value; drop_first=True, missing filled with 'u'; only the columns listed above are used, in this order", "gender": sorted(df.gender.fillna("u").unique().tolist()), "race": sorted(df.race.fillna("u").unique().tolist()), "state": sorted(df.state.fillna("u").unique().tolist()), "cur_rg": sorted(df.cur_rg.fillna("u").unique().tolist()), "prev_rg": sorted(df.prev_rg.fillna("u").unique().tolist()), "contact_type": sorted(df.contact_type.fillna("u").unique().tolist()), "encounter_type": sorted(df.encounter_type.fillna("u").unique().tolist())}, "reference_implementation": "scripts/02_features.py (feature construction), scripts/04_models.py (training)"}
json.dump(spec, open(OUT/"feature_spec.json", "w"), indent=1)
thr = {"flag_rule": "flag the 20% of contacts with the highest predicted probability", "validated_model_threshold_probability": round(float(np.quantile(p_tr, 0.8)), 4), "deploy_model_threshold_probability": round(float(np.quantile(p_all, 0.8)), 4), "deploy_model_decile_cutpoints": [round(float(q), 4) for q in np.quantile(p_all, np.arange(0.1, 1.0, 0.1))], "recalibrate": "re-estimate the threshold on the most recent completed quarter; refit the model quarterly"}
json.dump(thr, open(OUT/"thresholds.json", "w"), indent=1)
ss = json.load(open(R/"simple_score.json")); json.dump({"description": "hand-scorable points score; log-transformed counts enter as log(1+x) times the points; flag the 20% of contacts with the highest score", "predictors": ss["predictors"], "points": ss["points"], "logistic_coefficients": ss["coefficients"], "logistic_intercept": ss["intercept"], "test_performance": ss["points_score"]}, open(OUT/"points_score.json", "w"), indent=1)
ops = json.load(open(R/"ops_rule.json"))
json.dump({"when": "evaluate at day 7 after each completed contact", "flag_if": ["(a) predicted disengagement probability at the contact is at or above the 20% threshold (thresholds.json) or the points score is in its top 20%", "(b) no completed contact and no logged attempt (EncounterNote with encounterOccurred = 'NO') in days 1 to 7"], "order_list_by": "predicted return if attempted from the uplift model (uplift_*.joblib), highest first; do not use it to exclude patients", "test_set_performance_rule_ab": ops["rule_ab_risk_and_lapsed_unattended"], "test_set_performance_rule_abc": ops["rule_abc_on_test"], "monitoring": "monthly realized disengagement by predicted decile; flag rate and sensitivity by state and by race and ethnicity; refit quarterly"}, open(OUT/"day7_rule.json", "w"), indent=1)
# uplift T-learner on all lapsed episodes (same construction as scripts/27_ops_rule.py)
en = pd.read_parquet(D/"encounter_times_study.parquet"); en["t"] = pd.to_datetime(en.startTime.fillna(en.dateOfEncounter)); en = en.dropna(subset=["t"]); D1 = np.timedelta64(1, "D"); E0 = np.array([], dtype="datetime64[ns]")
fl = lambda v: np.sort(v.astype("datetime64[D]").astype("datetime64[ns]")); AT = {p: fl(g.t.values) for p, g in en[en.occurred == "NO"].groupby("person_id")}; CT = {p: fl(g.t.values) for p, g in en[en.occurred == "YES"].groupby("person_id")}
def cnt(arr, a, b): return int(np.searchsorted(arr, b, "right") - np.searchsorted(arr, a, "right"))
df["enc_date"] = pd.to_datetime(df.enc_date); t = df.enc_date.values.astype("datetime64[ns]"); pid = df.person_id.values
c17 = np.array([cnt(CT.get(p, E0), x, x + 7*D1) for p, x in zip(pid, t)]); a17 = np.array([cnt(AT.get(p, E0), x, x + 7*D1) for p, x in zip(pid, t)]); ret = np.array([int(cnt(CT.get(p, E0), x + 7*D1, x + 30*D1) > 0) for p, x in zip(pid, t)]); att30 = np.array([cnt(AT.get(p, E0), x - 31*D1, x - D1) for p, x in zip(pid, t)])
def prior_connect(p, x):
    a = AT.get(p, E0); c = CT.get(p, E0); a = a[a < x]
    return -1.0 if len(a) == 0 else float(np.mean([cnt(c, ai, ai + 2*D1) > 0 for ai in a[-10:]]))
pc = np.array([prior_connect(p, x) for p, x in zip(pid, t)]); comp = (t + 30*D1 <= np.datetime64("2026-06-07"))
UF = ["age","risk_percentile","days_from_zd","n_prior_90","att30","prior_connect","state_va","state_wa","inp","any_bh","adt_all_prior_365d"]
U = pd.DataFrame({"age": df.age, "risk_percentile": df.risk_percentile, "days_from_zd": df.days_from_zd, "n_prior_90": df.n_prior_90, "att30": att30, "prior_connect": pc, "state_va": (df.state == "VIRGINIA").astype(int), "state_wa": (df.state == "WASHINGTON").astype(int), "inp": df.contact_type.isin(["HOME_VISIT","OTHER_INPERSON","HOSPITAL","CBO","IN_COMMUNITY","PROVIDER_OFFICE"]).astype(int), "any_bh": df.any_bh, "adt_all_prior_365d": df.adt_all_prior_365d}).astype(float).fillna(0)
L = (c17 == 0) & comp; A = (a17 > 0).astype(int)
m1 = GradientBoostingRegressor(n_estimators=200, max_depth=3, learning_rate=0.05, random_state=1).fit(U.values[L & (A == 1)], ret[L & (A == 1)]); m0 = GradientBoostingRegressor(n_estimators=200, max_depth=3, learning_rate=0.05, random_state=1).fit(U.values[L & (A == 0)], ret[L & (A == 0)])
joblib.dump(m1, OUT/"uplift_return_if_attempted.joblib"); joblib.dump(m0, OUT/"uplift_return_if_not_attempted.joblib")
tau = m1.predict(U.values[L]) - m0.predict(U.values[L])
json.dump({"columns_in_order": UF, "definitions": {"prior_connect": "share of the patient's last 10 attempts before this contact that were followed by a completed contact within 2 days (-1 if no prior attempts)", "att30": "logged attempts in the 30 days before the contact", "inp": "this contact was in person", "state_va": "state is Virginia", "state_wa": "state is Washington"}, "uplift": "predict with both models on the same row; uplift = return_if_attempted - return_if_not_attempted", "median_uplift_among_lapsed_episodes": round(float(np.median(tau)), 4), "tertile_cutpoints": [round(float(q), 4) for q in np.quantile(tau, [1/3, 2/3])], "n_lapsed_episodes_fit": int(L.sum())}, open(OUT/"uplift_spec.json", "w"), indent=1)
print("exported:", sorted(p.name for p in OUT.iterdir())); print("validated threshold", thr["validated_model_threshold_probability"], "deploy threshold", thr["deploy_model_threshold_probability"], "| training AUROC check:", round(float(__import__("sklearn.metrics", fromlist=["roc_auc_score"]).roc_auc_score(y[~tr], m_val.predict_proba(X.values[~tr])[:,1])), 4))
